spring.application.name=uco-parking-backend
server.port=3000

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=UcoParking;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=UcoParking123*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver